### PR TITLE
Update to MC 1.14

### PR DESCRIPTION
**Pull request by Sataniel98**

### CODE REVIEW

**Comment by LordBanshee** [comment]
Still having issues from #182 on my server.

27.04 16:05:38 [Server] Server thread/INFO [Brewery] ERROR: Database failure! unable to find UID -80 of a custom Potion!
27.04 16:05:45 [Server] Server thread/INFO [Brewery] ERROR: Database failure! unable to find UID -76 of a custom Potion!

I'll continue to find a fix on my own end, but no luck so far.

**Comment by xkevio** [comment]
Same issue here even with this branch. #182 

1. The effects seem to disappear instantly
2. Doesn't matter which drink, even self-brewed coffee doesn't work.

[01:04:48] [Server thread/INFO]: [Brewery] ERROR: Database failure! unable to find UID -72 of a custom Potion!
-> When drinking Strong Coffee for example.
Hoping for a quick update, maybe something changed with the Potions and Effects in Spigot 1.14, I am not so sure.

**Comment by cheesepufftyler** [comment]
Same issue here. on the brewery version 1.7.2 and the server is running spigot 1.14. players can brew anything. same issue xkevio is having in console.

**Comment by ThatsHowMafia** [comment]
Same issue here. When players distilling potion.

05.05 18:23:18 [Server] Server thread/INFO [Brewery] ERROR: Database failure! unable to find UID -23 of a custom Potion!
05.05 18:23:24 [Server] Server thread/INFO [Brewery] ERROR: Database failure! unable to find UID -21 of a custom Potion!

**Comment by d00mduck101** [comment]
Any word on an update? I'm poking around myself rn, no real luck so far...

**Comment by Sn0wStorm** [comment]
I will have a look, maybe they changed the way potion ids work now

**Pull request merged**
