### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Includes a solid fix for potion colors (tested, works), some index fixes that are perhaps dodgy but if not addressed led to critical failures on my server, and support for CivCraft's (now DevotedMC's) Citadel plugin. I know of several servers either actively using Brewery and Citadel in combination or planning to, so would be a nice upstream add.

Let me know if you'd prefer the fixes without the integration, and I'll make a clean PR with just those things.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Ah, sorry about the CI fail, just saw I needed to renew my CI's cert. Done now.

**Comment by JohOply** [comment]
Hi ProgrammerDan, are you able to compile and release it please?

**Comment by JohOply** [comment]
Hi @ProgrammerDan , are you able to compile and release it please?

**Comment by Sataniel98** [comment]
I'm not sure if @Sn0wStorm is still around now and again. His server runs 1.8.x as far as I know and he doesn't have any other public plugins except Brewery (which is in a solid state after all), so I guess he doesn't visit GitHub regularly. I'll try to contact him if he doesn't answer.

**Comment by ProgrammerDan** [comment]
@JohOply https://github.com/DevotedMC/Brewery/releases/tag/1.6.1

Hope that helps. Been running it for a while now, works great, seems to work great with 1.12.1 too.

**Comment by JohOply** [comment]
@ProgrammerDan Thank you I will try it

**Pull request merged**
