### PR TITLE
Fix DieReicheErethons/Brewery#119

### PR DESCRIPTION
**Pull request by Sataniel98**
I'm using an unofficial, but working repository.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Looks like the build just fails due to the .zip file error as described in #119 . I'd hazard this isn't fixed yet :-/

**Comment by Sataniel98** [comment]
I don't get a zip error...

**Comment by Sn0wStorm** [comment]
Maven tries (and somehow succeeds) to download this file  
Downloaded: http://feuerstern.bplaced.net/repo/de/diddiz/logblock/1.94/logblock-1.94.jar (7 KB at 18.1 KB/sec)

Which is downloaded as an invalid 7kb file and then produces the zip error.

**Comment by Sataniel98** [comment]
Okay, I found my mistake... My repo must be the last one in the repo list to make it work with a clean local repo because fetching jars from mine technically can't fail. It seems Maven fetches and renames an error page to *.jar... -.- If the LB repo is listed above, Maven downloads LogBlock before the error can occur. I'm sorry ¯\_(ツ)_/¯

**Pull request merged**
