### PR TITLE
Add the ability to use lava and powdered snow as liquids

### PR DESCRIPTION
**Pull request by pontaoski**

### CODE REVIEW

**Comment by pontaoski** [comment]
ping @Sn0wStorm

**Comment by Fever2121** [comment]
@Sn0wStorm are you still alive?

**Comment by Sn0wStorm** [comment]
@Fever2121 Hey yes i'm actually still here :D I have not got much time for Brewery though, so won't be able to add many new features. I've actually looked at this PR a while ago already, but never came around to reviewing and merging this, hopefully will have some time to do it now.

**Comment by pontaoski** [comment]
sorry, i'm no longer interested in contributing to brewery

**Pull request closed without merging**
